### ISSUE TITLE
Error when printing negative numbers

### ISSUE THREAD

**Issue by DiegoMagdaleno** [eltanin-os/tertium#1]
Hi! I have been interested in this project since a year ago (I emailed you a while ago about it)

I love your implementation of the libraries, so much that when I started making my own OS (which also uses the Linux kernel, but has some differences), I decided to make a library inspired by yours.

When I started implementing my library, I first tested some of the tertium functionality, and it seems it can't really handle negative numbers when printing with `%d`.

The error seems to be related to the way `va_arg` grabs the argument, as I got it to print negative numbers when I grabbed them with `int`instead of `uvlong`, however, it looks like this "hack fix" broke other stuff.

I have been debugging this error for quite a while with the intention of contributing back a fix, but I don't seem to be able to find where the error is located.

Is this intentional?, Due to the nature of Tertium it might be intentional that said values fail to properly print, unless some other format specifier specifies the number can be negative.

So far I found these resources talking about a similar error:
https://stackoverflow.com/questions/57748347/why-can-i-import-negative-numbers-as-int-but-not-as-long-int-or-other-larger-da

Btw, if I use:
`c_ioq_fmt(ioq2, "Negative values: %d", -1L);`

It does work.

So I can't wrap my head around why this isn't working, I have looked at other implementations, such as Plan 9 (which is similar to this one) and Musl and while they seem to have different logic, it looks like they use `unions` and other mechanisms to extract the proper data size.

**Comment by eadwardus** [comment]
Hello there,
It was a known bug, but I didn't had intention to keep it, however, as I didn't have real problems with it, I was delaying the solution (also because initially was convenient that '%d' would print every number, even though it's probably undefined behaviour as va_list implementations may vary).

I suppose it should be quite easy to fix, the problem of the conversion is considering the value type a "vlong" (long long), so a value that would be considered negative to an "int" will still be considered positive. Dealing with each type separately should fix it, also would avoid reading more data than it should (this one I suppose is undefined behaviour, could work forever, or fail randomly).

Thanks for the report, I'll make more tests about this behaviour and fix it in the next minor release, for now you could try this patch (I did it now for testing, seems to mimic the printf output correctly, but I didn't test it too much):
[tertium_int_verb_size.txt](https://github.com/eltanin-os/tertium/files/8986933/tertium_int_verb_size.txt)

As I did many significant changes it may suck to build now (because it uses redo now, but my implementation has a difference from the other implementations), you can find one redo binary already compiled (statically) at:
https://downloads.eltaninos.org/repo/binaries/x86_64-buildcore.tar.lz

I'll try to provide a bootstrap to it later.

**Comment by DiegoMagdaleno** [comment]
Thanks! I'll try it and see if it works now.

And yes, apparently the biggest issue with the current way Tertium retrieves the data, is that retrieving into a longer datatype (in this case I think ulong is 8 bytes) vs int (being 4 bytes) is undefined behavior.

I can confirm this patch fixes the issue :D, thank you.
